version: '3.7'

services:

  server:
    image: registry.gitlab.com/jgsandlin/demo-flask:release_8266c4d8
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 5000:5000
      #- 80:80
    environment:
      - FLASK_ENV=development
